# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug64
endif
export config

PROJECTS := tevo

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

tevo:
	@echo "==== Building tevo ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f tevo.make

clean:
	@${MAKE} --no-print-directory -C . -f tevo.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug64"
	@echo "   release64"
	@echo "   debug32"
	@echo "   release32"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   tevo"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
